/* The following code was generated by JFlex 1.4.3 on 29/11/22 02:29 PM */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 29/11/22 02:29 PM from the specification file
 * <tt>../AnalizadorFinal/src/codigo/Lexico.flex</tt>
 */
class Lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\34\2\0\1\3\22\0\1\3\1\47\1\37\1\5"+
    "\1\0\1\44\1\45\1\0\1\52\1\53\1\43\1\41\1\62\1\42"+
    "\1\4\1\35\12\2\1\61\1\60\1\51\1\40\1\50\1\0\1\63"+
    "\16\1\1\1\3\1\1\36\7\1\1\56\1\0\1\57\1\0\1\1"+
    "\1\0\1\22\1\24\1\10\1\13\1\14\1\15\1\27\1\26\1\6"+
    "\1\1\1\25\1\11\1\23\1\7\1\16\1\32\1\1\1\21\1\17"+
    "\1\20\1\12\1\33\1\31\1\1\1\30\1\1\1\54\1\46\1\55"+
    "\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\20\2"+
    "\1\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\2\0\1\2\1\36\12\2\1\37\23\2\1\4\1\40"+
    "\1\2\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\3\1\0\1\3\1\0\1\2\1\60\2\2\1\61"+
    "\14\2\1\62\2\2\1\63\17\2\2\0\1\64\5\2"+
    "\1\65\1\66\1\67\1\70\5\2\1\71\1\72\6\2"+
    "\1\73\3\2\1\74\1\75\1\2\1\76\2\2\1\77"+
    "\1\2\2\44\1\0\3\2\1\100\2\2\1\101\3\2"+
    "\1\102\1\103\1\104\1\2\1\105\4\2\1\106\1\107"+
    "\7\2\1\110\1\2\1\111\1\112\1\113\1\2\1\114"+
    "\1\2\1\115\1\116\1\117\4\2\1\120\1\121\1\2"+
    "\1\122\1\2\1\123\1\124\1\125\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\64\0\64\0\u0104"+
    "\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\64"+
    "\0\u0444\0\u0478\0\64\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c"+
    "\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\64\0\u06b4"+
    "\0\u06e8\0\u071c\0\150\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60"+
    "\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00"+
    "\0\u0d34\0\u0d68\0\64\0\u0d9c\0\64\0\64\0\64\0\u0dd0"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\u0e04\0\u0e38\0\u0e6c\0\u0e6c\0\u0ea0"+
    "\0\150\0\u0ed4\0\u0f08\0\150\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8"+
    "\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178"+
    "\0\150\0\u11ac\0\u11e0\0\150\0\u1214\0\u1248\0\u127c\0\u12b0"+
    "\0\u12e4\0\u1318\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450"+
    "\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u1554\0\u1588\0\u15bc\0\u15f0"+
    "\0\u1624\0\u1658\0\u168c\0\150\0\150\0\150\0\150\0\u16c0"+
    "\0\u16f4\0\u1728\0\u175c\0\u1790\0\150\0\150\0\u17c4\0\u17f8"+
    "\0\u182c\0\u1860\0\u1894\0\u18c8\0\150\0\u18fc\0\u1930\0\u1964"+
    "\0\150\0\150\0\u1998\0\150\0\u19cc\0\u1a00\0\150\0\u1a34"+
    "\0\u1a68\0\u1a9c\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38\0\150\0\u1b6c"+
    "\0\u1ba0\0\150\0\u1bd4\0\u1c08\0\u1c3c\0\150\0\150\0\150"+
    "\0\u1c70\0\150\0\u1ca4\0\u1cd8\0\u1d0c\0\u1d40\0\150\0\150"+
    "\0\u1d74\0\u1da8\0\u1ddc\0\u1e10\0\u1e44\0\u1e78\0\u1eac\0\150"+
    "\0\u1ee0\0\150\0\150\0\150\0\u1f14\0\150\0\u1f48\0\150"+
    "\0\150\0\150\0\u1f7c\0\u1fb0\0\u1fe4\0\u2018\0\150\0\150"+
    "\0\u204c\0\150\0\u2080\0\150\0\150\0\150\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\3\1\20"+
    "\1\21\1\22\1\3\1\23\1\24\4\3\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\65\0\2\3\3\0\26\3\2\0\1\3\27\0"+
    "\1\4\1\0\1\60\7\0\1\61\52\0\1\5\61\0"+
    "\2\3\3\0\1\3\1\62\5\3\1\63\1\64\15\3"+
    "\2\0\1\3\26\0\2\3\3\0\14\3\1\65\11\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\66\7\3\1\67"+
    "\3\3\1\70\3\3\1\71\5\3\2\0\1\3\26\0"+
    "\2\3\3\0\10\3\1\72\15\3\2\0\1\3\26\0"+
    "\2\3\3\0\1\3\1\73\7\3\1\74\14\3\2\0"+
    "\1\3\26\0\2\3\3\0\6\3\1\75\1\3\1\76"+
    "\15\3\2\0\1\3\26\0\2\3\3\0\1\3\1\77"+
    "\1\3\1\100\22\3\2\0\1\3\26\0\2\3\3\0"+
    "\3\3\1\101\4\3\1\102\3\3\1\103\11\3\2\0"+
    "\1\3\26\0\2\3\3\0\2\3\1\104\7\3\1\105"+
    "\5\3\1\106\2\3\1\107\2\3\2\0\1\3\26\0"+
    "\2\3\3\0\13\3\1\110\6\3\1\111\3\3\2\0"+
    "\1\3\26\0\2\3\3\0\6\3\1\112\17\3\2\0"+
    "\1\3\26\0\2\3\3\0\14\3\1\113\11\3\2\0"+
    "\1\3\26\0\2\3\3\0\10\3\1\114\2\3\1\115"+
    "\6\3\1\116\3\3\2\0\1\3\26\0\2\3\3\0"+
    "\20\3\1\117\5\3\2\0\1\3\26\0\2\3\3\0"+
    "\13\3\1\120\12\3\2\0\1\3\26\0\2\3\3\0"+
    "\10\3\1\121\15\3\2\0\1\3\62\0\1\122\2\0"+
    "\1\123\24\0\2\3\3\0\12\3\1\124\13\3\2\0"+
    "\1\3\65\0\1\125\63\0\1\126\1\127\24\0\1\130"+
    "\35\0\1\131\1\0\1\132\61\0\1\133\63\0\1\134"+
    "\70\0\1\135\64\0\1\136\55\0\1\137\63\0\1\140"+
    "\7\0\1\141\53\0\1\142\10\0\1\143\14\0\1\144"+
    "\1\0\1\145\61\0\1\146\36\0\2\147\22\0\2\3"+
    "\3\0\2\3\1\150\7\3\1\151\13\3\2\0\1\3"+
    "\26\0\2\3\3\0\11\3\1\152\14\3\2\0\1\3"+
    "\26\0\2\3\3\0\15\3\1\153\10\3\2\0\1\3"+
    "\26\0\2\3\3\0\1\3\1\154\24\3\2\0\1\3"+
    "\26\0\2\3\3\0\1\3\1\155\2\3\1\156\21\3"+
    "\2\0\1\3\26\0\2\3\3\0\11\3\1\157\14\3"+
    "\2\0\1\3\26\0\2\3\3\0\14\3\1\160\11\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\3\1\161\24\3"+
    "\2\0\1\3\26\0\2\3\3\0\11\3\1\162\14\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\163\25\3\2\0"+
    "\1\3\26\0\2\3\3\0\7\3\1\164\16\3\2\0"+
    "\1\3\26\0\2\3\3\0\4\3\1\165\21\3\2\0"+
    "\1\3\26\0\2\3\3\0\5\3\1\166\20\3\2\0"+
    "\1\3\26\0\2\3\3\0\11\3\1\167\14\3\2\0"+
    "\1\3\26\0\2\3\3\0\10\3\1\170\15\3\2\0"+
    "\1\3\26\0\2\3\3\0\13\3\1\171\12\3\2\0"+
    "\1\3\26\0\2\3\3\0\3\3\1\172\22\3\2\0"+
    "\1\3\26\0\2\3\3\0\14\3\1\173\11\3\2\0"+
    "\1\3\26\0\2\3\3\0\5\3\1\174\5\3\1\175"+
    "\12\3\2\0\1\3\26\0\2\3\3\0\10\3\1\176"+
    "\15\3\2\0\1\3\26\0\2\3\3\0\1\177\25\3"+
    "\2\0\1\3\26\0\2\3\3\0\4\3\1\200\21\3"+
    "\2\0\1\3\26\0\2\3\3\0\24\3\1\201\1\3"+
    "\2\0\1\3\26\0\2\3\3\0\12\3\1\202\6\3"+
    "\1\203\4\3\2\0\1\3\26\0\2\3\3\0\1\204"+
    "\25\3\2\0\1\3\26\0\2\3\3\0\10\3\1\205"+
    "\15\3\2\0\1\3\26\0\2\3\3\0\6\3\1\206"+
    "\17\3\2\0\1\3\26\0\2\3\3\0\12\3\1\207"+
    "\13\3\2\0\1\3\26\0\2\3\3\0\1\210\25\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\211\25\3\2\0"+
    "\1\3\26\0\2\3\3\0\1\212\25\3\2\0\1\3"+
    "\25\0\34\122\1\0\27\122\1\0\2\3\3\0\13\3"+
    "\1\213\12\3\2\0\1\3\27\0\1\130\1\0\1\214"+
    "\7\0\1\215\51\0\1\144\11\0\1\61\51\0\1\216"+
    "\1\0\1\145\61\0\1\146\62\0\2\3\3\0\3\3"+
    "\1\217\22\3\2\0\1\3\26\0\2\3\3\0\12\3"+
    "\1\220\13\3\2\0\1\3\26\0\2\3\3\0\6\3"+
    "\1\221\17\3\2\0\1\3\26\0\2\3\3\0\11\3"+
    "\1\222\1\223\13\3\2\0\1\3\26\0\2\3\3\0"+
    "\12\3\1\224\13\3\2\0\1\3\26\0\2\3\3\0"+
    "\6\3\1\225\17\3\2\0\1\3\26\0\2\3\3\0"+
    "\13\3\1\226\12\3\2\0\1\3\26\0\2\3\3\0"+
    "\21\3\1\227\4\3\2\0\1\3\26\0\2\3\3\0"+
    "\1\230\25\3\2\0\1\3\26\0\2\3\3\0\1\3"+
    "\1\231\24\3\2\0\1\3\26\0\2\3\3\0\1\232"+
    "\13\3\1\233\11\3\2\0\1\3\26\0\2\3\3\0"+
    "\16\3\1\234\7\3\2\0\1\3\26\0\2\3\3\0"+
    "\3\3\1\235\22\3\2\0\1\3\26\0\2\3\3\0"+
    "\6\3\1\236\17\3\2\0\1\3\26\0\2\3\3\0"+
    "\14\3\1\237\11\3\2\0\1\3\26\0\2\3\3\0"+
    "\11\3\1\240\14\3\2\0\1\3\26\0\2\3\3\0"+
    "\1\3\1\241\24\3\2\0\1\3\26\0\2\3\3\0"+
    "\4\3\1\242\21\3\2\0\1\3\26\0\2\3\3\0"+
    "\13\3\1\243\12\3\2\0\1\3\26\0\2\3\3\0"+
    "\12\3\1\244\13\3\2\0\1\3\26\0\2\3\3\0"+
    "\6\3\1\245\17\3\2\0\1\3\26\0\2\3\3\0"+
    "\6\3\1\246\17\3\2\0\1\3\26\0\2\3\3\0"+
    "\4\3\1\247\21\3\2\0\1\3\26\0\2\3\3\0"+
    "\1\250\25\3\2\0\1\3\26\0\2\3\3\0\1\3"+
    "\1\251\24\3\2\0\1\3\26\0\2\3\3\0\3\3"+
    "\1\252\22\3\2\0\1\3\26\0\2\3\3\0\14\3"+
    "\1\253\11\3\2\0\1\3\26\0\2\3\3\0\6\3"+
    "\1\254\17\3\2\0\1\3\26\0\2\3\3\0\3\3"+
    "\1\255\22\3\2\0\1\3\26\0\2\3\3\0\1\3"+
    "\1\256\24\3\2\0\1\3\26\0\2\3\3\0\5\3"+
    "\1\257\20\3\2\0\1\3\26\0\2\3\3\0\1\260"+
    "\25\3\2\0\1\3\27\0\1\261\1\0\1\145\61\0"+
    "\1\262\36\0\2\263\23\0\1\216\62\0\2\3\3\0"+
    "\4\3\1\264\21\3\2\0\1\3\26\0\2\3\3\0"+
    "\13\3\1\265\12\3\2\0\1\3\26\0\2\3\3\0"+
    "\11\3\1\266\14\3\2\0\1\3\26\0\2\3\3\0"+
    "\12\3\1\267\13\3\2\0\1\3\26\0\2\3\3\0"+
    "\1\270\25\3\2\0\1\3\26\0\2\3\3\0\21\3"+
    "\1\271\4\3\2\0\1\3\26\0\2\3\3\0\21\3"+
    "\1\272\4\3\2\0\1\3\26\0\2\3\3\0\1\3"+
    "\1\273\24\3\2\0\1\3\26\0\2\3\3\0\4\3"+
    "\1\274\21\3\2\0\1\3\26\0\2\3\3\0\3\3"+
    "\1\275\22\3\2\0\1\3\26\0\2\3\3\0\12\3"+
    "\1\276\13\3\2\0\1\3\26\0\2\3\3\0\6\3"+
    "\1\277\17\3\2\0\1\3\26\0\2\3\3\0\7\3"+
    "\1\300\16\3\2\0\1\3\26\0\2\3\3\0\2\3"+
    "\1\301\23\3\2\0\1\3\26\0\2\3\3\0\12\3"+
    "\1\302\13\3\2\0\1\3\26\0\2\3\3\0\2\3"+
    "\1\303\23\3\2\0\1\3\26\0\2\3\3\0\5\3"+
    "\1\304\20\3\2\0\1\3\26\0\2\3\3\0\13\3"+
    "\1\305\12\3\2\0\1\3\26\0\2\3\3\0\11\3"+
    "\1\306\14\3\2\0\1\3\26\0\2\3\3\0\17\3"+
    "\1\307\6\3\2\0\1\3\26\0\2\3\3\0\6\3"+
    "\1\310\17\3\2\0\1\3\26\0\2\3\3\0\12\3"+
    "\1\311\13\3\2\0\1\3\26\0\2\3\3\0\1\3"+
    "\1\312\24\3\2\0\1\3\27\0\1\261\11\0\1\215"+
    "\51\0\1\262\62\0\2\3\3\0\5\3\1\313\20\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\314\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\24\3\1\315\1\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\3\1\316\24\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\3\1\317\24\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\320\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\3\3\1\321\22\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\322\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\12\3\1\323\13\3"+
    "\2\0\1\3\26\0\2\3\3\0\20\3\1\324\5\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\325\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\1\3\1\326\24\3"+
    "\2\0\1\3\26\0\2\3\3\0\12\3\1\327\13\3"+
    "\2\0\1\3\26\0\2\3\3\0\7\3\1\330\16\3"+
    "\2\0\1\3\26\0\2\3\3\0\21\3\1\331\4\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\332\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\14\3\1\333\11\3"+
    "\2\0\1\3\26\0\2\3\3\0\14\3\1\334\11\3"+
    "\2\0\1\3\26\0\2\3\3\0\4\3\1\335\21\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\336\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\12\3\1\337\13\3"+
    "\2\0\1\3\26\0\2\3\3\0\7\3\1\340\16\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\341\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\15\3\1\342\10\3"+
    "\2\0\1\3\26\0\2\3\3\0\2\3\1\343\23\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\344\17\3"+
    "\2\0\1\3\26\0\2\3\3\0\5\3\1\345\20\3"+
    "\2\0\1\3\26\0\2\3\3\0\13\3\1\346\12\3"+
    "\2\0\1\3\26\0\2\3\3\0\6\3\1\347\17\3"+
    "\2\0\1\3\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8372];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\20\1\1\11\2\1\1\11"+
    "\12\1\12\11\2\0\41\1\1\11\1\1\3\11\1\1"+
    "\13\11\1\1\1\0\1\1\1\0\44\1\2\0\45\1"+
    "\1\0\64\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexemas;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { lexemas=yytext(); return Conjuncion;
          }
        case 87: break;
        case 74: 
          { lexemas=yytext(); return Struct;
          }
        case 88: break;
        case 23: 
          { lexemas=yytext(); return Llave_c;
          }
        case 89: break;
        case 76: 
          { lexemas=yytext(); return Return;
          }
        case 90: break;
        case 11: 
          { lexemas=yytext(); return Suma;
          }
        case 91: break;
        case 50: 
          { lexemas=yytext(); return For;
          }
        case 92: break;
        case 46: 
          { lexemas=yytext(); return MenorIgual;
          }
        case 93: break;
        case 27: 
          { lexemas=yytext(); return DosPuntos;
          }
        case 94: break;
        case 75: 
          { lexemas=yytext(); return Switch;
          }
        case 95: break;
        case 47: 
          { lexemas=yytext(); return DesplazamientoI;
          }
        case 96: break;
        case 12: 
          { lexemas=yytext(); return Resta;
          }
        case 97: break;
        case 16: 
          { lexemas=yytext(); return DisyuncionBit;
          }
        case 98: break;
        case 36: 
          { lexemas=yytext(); return NumeroR_negativo;
          }
        case 99: break;
        case 9: 
          { lexemas=yytext(); return Comillas;
          }
        case 100: break;
        case 44: 
          { lexemas=yytext(); return MayorIgual;
          }
        case 101: break;
        case 40: 
          { lexemas=yytext(); return AsignacionModulo;
          }
        case 102: break;
        case 8: 
          { lexemas=yytext(); return Division;
          }
        case 103: break;
        case 6: 
          { lexemas=yytext(); return Numeral;
          }
        case 104: break;
        case 67: 
          { lexemas=yytext(); return False;
          }
        case 105: break;
        case 10: 
          { lexemas=yytext(); return Igual;
          }
        case 106: break;
        case 56: 
          { lexemas=yytext(); return Long;
          }
        case 107: break;
        case 13: 
          { lexemas=yytext(); return Multiplicacion;
          }
        case 108: break;
        case 4: 
          { /*Ignore*/
          }
        case 109: break;
        case 61: 
          { lexemas=yytext(); return Bool;
          }
        case 110: break;
        case 39: 
          { lexemas=yytext(); return AsignacionMultiplicacion;
          }
        case 111: break;
        case 81: 
          { lexemas=yytext(); return Typedef;
          }
        case 112: break;
        case 30: 
          { lexemas=yytext(); return If;
          }
        case 113: break;
        case 82: 
          { lexemas=yytext(); return Iostream;
          }
        case 114: break;
        case 79: 
          { lexemas=yytext(); return Include;
          }
        case 115: break;
        case 66: 
          { lexemas=yytext(); return Float;
          }
        case 116: break;
        case 55: 
          { lexemas=yytext(); return Char;
          }
        case 117: break;
        case 22: 
          { lexemas=yytext(); return Llave_a;
          }
        case 118: break;
        case 34: 
          { lexemas=yytext(); return AsignacionSuma;
          }
        case 119: break;
        case 72: 
          { lexemas=yytext(); return Define;
          }
        case 120: break;
        case 1: 
          { return ERROR;
          }
        case 121: break;
        case 5: 
          { lexemas=yytext(); return Punto;
          }
        case 122: break;
        case 84: 
          { lexemas=yytext(); return Unsigned;
          }
        case 123: break;
        case 17: 
          { lexemas=yytext(); return Negacion;
          }
        case 124: break;
        case 25: 
          { lexemas=yytext(); return Corchete_c;
          }
        case 125: break;
        case 85: 
          { lexemas=yytext(); return Register;
          }
        case 126: break;
        case 35: 
          { lexemas=yytext(); return Incremento;
          }
        case 127: break;
        case 33: 
          { lexemas=yytext(); return EsIgual;
          }
        case 128: break;
        case 62: 
          { lexemas=yytext(); return Byte;
          }
        case 129: break;
        case 80: 
          { lexemas=yytext(); return Default;
          }
        case 130: break;
        case 14: 
          { lexemas=yytext(); return Modulo;
          }
        case 131: break;
        case 42: 
          { lexemas=yytext(); return Disyuncion;
          }
        case 132: break;
        case 51: 
          { lexemas=yytext(); return Std;
          }
        case 133: break;
        case 53: 
          { lexemas=yytext(); return Cout;
          }
        case 134: break;
        case 37: 
          { lexemas=yytext(); return AsignacionResta;
          }
        case 135: break;
        case 69: 
          { lexemas=yytext(); return Short;
          }
        case 136: break;
        case 58: 
          { lexemas=yytext(); return Else;
          }
        case 137: break;
        case 21: 
          { lexemas=yytext(); return Parent_c;
          }
        case 138: break;
        case 77: 
          { lexemas=yytext(); return PrintF;
          }
        case 139: break;
        case 60: 
          { lexemas=yytext(); return Main;
          }
        case 140: break;
        case 2: 
          { lexemas=yytext(); return Identificador;
          }
        case 141: break;
        case 26: 
          { lexemas=yytext(); return P_coma;
          }
        case 142: break;
        case 43: 
          { lexemas=yytext(); return Diferente;
          }
        case 143: break;
        case 71: 
          { lexemas=yytext(); return While;
          }
        case 144: break;
        case 54: 
          { lexemas=yytext(); return Case;
          }
        case 145: break;
        case 19: 
          { lexemas=yytext(); return MenorQue;
          }
        case 146: break;
        case 15: 
          { lexemas=yytext(); return ConjuncionBit;
          }
        case 147: break;
        case 38: 
          { lexemas=yytext(); return Decremento;
          }
        case 148: break;
        case 68: 
          { lexemas=yytext(); return ScanF;
          }
        case 149: break;
        case 7: 
          { return Linea;
          }
        case 150: break;
        case 24: 
          { lexemas=yytext(); return Corchete_a;
          }
        case 151: break;
        case 64: 
          { lexemas=yytext(); return Const;
          }
        case 152: break;
        case 86: 
          { lexemas=yytext(); return Namespace;
          }
        case 153: break;
        case 29: 
          { lexemas=yytext(); return Arroba;
          }
        case 154: break;
        case 49: 
          { lexemas=yytext(); return Cin;
          }
        case 155: break;
        case 59: 
          { lexemas=yytext(); return True;
          }
        case 156: break;
        case 48: 
          { lexemas=yytext(); return Int;
          }
        case 157: break;
        case 70: 
          { lexemas=yytext(); return Break;
          }
        case 158: break;
        case 78: 
          { lexemas=yytext(); return Cadena;
          }
        case 159: break;
        case 28: 
          { lexemas=yytext(); return Coma;
          }
        case 160: break;
        case 65: 
          { lexemas=yytext(); return Using;
          }
        case 161: break;
        case 18: 
          { lexemas=yytext(); return MayorQue;
          }
        case 162: break;
        case 52: 
          { lexemas=yytext(); return Numero;
          }
        case 163: break;
        case 45: 
          { lexemas=yytext(); return DesplazamientoD;
          }
        case 164: break;
        case 63: 
          { lexemas=yytext(); return Void;
          }
        case 165: break;
        case 3: 
          { lexemas=yytext(); return NumeroR;
          }
        case 166: break;
        case 32: 
          { lexemas=yytext(); return AsignacionDivision;
          }
        case 167: break;
        case 20: 
          { lexemas=yytext(); return Parent_a;
          }
        case 168: break;
        case 73: 
          { lexemas=yytext(); return Double;
          }
        case 169: break;
        case 31: 
          { lexemas=yytext(); return Do;
          }
        case 170: break;
        case 57: 
          { lexemas=yytext(); return Endl;
          }
        case 171: break;
        case 83: 
          { lexemas=yytext(); return Continue;
          }
        case 172: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
