
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 29 14:29:24 COT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Return = 22;
  public static final int Llave_c = 65;
  public static final int Incremento = 58;
  public static final int Llave_a = 64;
  public static final int Std = 79;
  public static final int Conjuncion = 40;
  public static final int PrintF = 73;
  public static final int Coma = 72;
  public static final int Linea = 2;
  public static final int Break = 7;
  public static final int Parent_c = 63;
  public static final int Parent_a = 62;
  public static final int Corchete_c = 67;
  public static final int MenorQue = 44;
  public static final int Corchete_a = 66;
  public static final int True = 60;
  public static final int Long = 20;
  public static final int Punto = 70;
  public static final int Default = 12;
  public static final int Char = 9;
  public static final int Decremento = 59;
  public static final int AsignacionModulo = 57;
  public static final int For = 16;
  public static final int Void = 30;
  public static final int DosPuntos = 71;
  public static final int Else = 18;
  public static final int Resta = 36;
  public static final int Int = 19;
  public static final int Cin = 75;
  public static final int DesplazamientoI = 51;
  public static final int Using = 77;
  public static final int Suma = 35;
  public static final int ERROR = 83;
  public static final int DesplazamientoD = 52;
  public static final int Cadena = 32;
  public static final int Typedef = 29;
  public static final int MenorIgual = 48;
  public static final int Main = 68;
  public static final int Do = 13;
  public static final int Disyuncion = 41;
  public static final int P_coma = 69;
  public static final int Unsigned = 26;
  public static final int MayorQue = 43;
  public static final int Short = 23;
  public static final int AsignacionMultiplicacion = 55;
  public static final int Case = 8;
  public static final int EsIgual = 45;
  public static final int Const = 10;
  public static final int Endl = 80;
  public static final int Continue = 11;
  public static final int Byte = 24;
  public static final int Numeral = 3;
  public static final int If = 17;
  public static final int MayorIgual = 47;
  public static final int Define = 5;
  public static final int EOF = 0;
  public static final int AsignacionResta = 54;
  public static final int Bool = 25;
  public static final int Cout = 76;
  public static final int Numero = 82;
  public static final int ScanF = 74;
  public static final int Double = 14;
  public static final int Struct = 27;
  public static final int Division = 38;
  public static final int Namespace = 78;
  public static final int error = 1;
  public static final int False = 61;
  public static final int Diferente = 46;
  public static final int Comillas = 33;
  public static final int Float = 15;
  public static final int DisyuncionBit = 50;
  public static final int AsignacionDivision = 56;
  public static final int AsignacionSuma = 53;
  public static final int Identificador = 81;
  public static final int Iostream = 6;
  public static final int Negacion = 42;
  public static final int Include = 4;
  public static final int Modulo = 39;
  public static final int ConjuncionBit = 49;
  public static final int Register = 21;
  public static final int Igual = 34;
  public static final int While = 31;
  public static final int Multiplicacion = 37;
  public static final int Switch = 28;
}

